/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedCamerasRouteImport } from './routes/_authenticated/cameras'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnergyRouteImport } from './routes/_authenticated/energy'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedScenesRouteImport } from './routes/_authenticated/scenes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedVacuumRouteImport } from './routes/_authenticated/vacuum'
import { Route as AuthenticatedAlexaDeviceIdRouteImport } from './routes/_authenticated/alexa.$deviceId'
import { Route as AuthenticatedAlexaCallbackRouteImport } from './routes/_authenticated/alexa.callback'
import { Route as AuthenticatedDeviceDeviceIdRouteImport } from './routes/_authenticated/device.$deviceId'
import { Route as AuthenticatedIntegrationIntegrationIdRouteImport } from './routes/_authenticated/integration.$integrationId'
import { Route as AuthenticatedRoomRoomIdRouteImport } from './routes/_authenticated/room.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCamerasRoute = AuthenticatedCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnergyRoute = AuthenticatedEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScenesRoute = AuthenticatedScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVacuumRoute = AuthenticatedVacuumRouteImport.update({
  id: '/vacuum',
  path: '/vacuum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlexaDeviceIdRoute =
  AuthenticatedAlexaDeviceIdRouteImport.update({
    id: '/alexa/$deviceId',
    path: '/alexa/$deviceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlexaCallbackRoute =
  AuthenticatedAlexaCallbackRouteImport.update({
    id: '/alexa/callback',
    path: '/alexa/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeviceDeviceIdRoute =
  AuthenticatedDeviceDeviceIdRouteImport.update({
    id: '/device/$deviceId',
    path: '/device/$deviceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationIntegrationIdRoute =
  AuthenticatedIntegrationIntegrationIdRouteImport.update({
    id: '/integration/$integrationId',
    path: '/integration/$integrationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomRoomIdRoute = AuthenticatedRoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/energy': typeof AuthenticatedEnergyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/scenes': typeof AuthenticatedScenesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/status': typeof AuthenticatedStatusRoute
  '/vacuum': typeof AuthenticatedVacuumRoute
  '/alexa/$deviceId': typeof AuthenticatedAlexaDeviceIdRoute
  '/alexa/callback': typeof AuthenticatedAlexaCallbackRoute
  '/device/$deviceId': typeof AuthenticatedDeviceDeviceIdRoute
  '/integration/$integrationId': typeof AuthenticatedIntegrationIntegrationIdRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/cameras': typeof AuthenticatedCamerasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/energy': typeof AuthenticatedEnergyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/scenes': typeof AuthenticatedScenesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/status': typeof AuthenticatedStatusRoute
  '/vacuum': typeof AuthenticatedVacuumRoute
  '/alexa/$deviceId': typeof AuthenticatedAlexaDeviceIdRoute
  '/alexa/callback': typeof AuthenticatedAlexaCallbackRoute
  '/device/$deviceId': typeof AuthenticatedDeviceDeviceIdRoute
  '/integration/$integrationId': typeof AuthenticatedIntegrationIntegrationIdRoute
  '/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/cameras': typeof AuthenticatedCamerasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/energy': typeof AuthenticatedEnergyRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/scenes': typeof AuthenticatedScenesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/vacuum': typeof AuthenticatedVacuumRoute
  '/_authenticated/alexa/$deviceId': typeof AuthenticatedAlexaDeviceIdRoute
  '/_authenticated/alexa/callback': typeof AuthenticatedAlexaCallbackRoute
  '/_authenticated/device/$deviceId': typeof AuthenticatedDeviceDeviceIdRoute
  '/_authenticated/integration/$integrationId': typeof AuthenticatedIntegrationIntegrationIdRoute
  '/_authenticated/room/$roomId': typeof AuthenticatedRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automations'
    | '/cameras'
    | '/dashboard'
    | '/energy'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/setup'
    | '/status'
    | '/vacuum'
    | '/alexa/$deviceId'
    | '/alexa/callback'
    | '/device/$deviceId'
    | '/integration/$integrationId'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automations'
    | '/cameras'
    | '/dashboard'
    | '/energy'
    | '/home'
    | '/insights'
    | '/integrations'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/setup'
    | '/status'
    | '/vacuum'
    | '/alexa/$deviceId'
    | '/alexa/callback'
    | '/device/$deviceId'
    | '/integration/$integrationId'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/automations'
    | '/_authenticated/cameras'
    | '/_authenticated/dashboard'
    | '/_authenticated/energy'
    | '/_authenticated/home'
    | '/_authenticated/insights'
    | '/_authenticated/integrations'
    | '/_authenticated/rooms'
    | '/_authenticated/scenes'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/status'
    | '/_authenticated/vacuum'
    | '/_authenticated/alexa/$deviceId'
    | '/_authenticated/alexa/callback'
    | '/_authenticated/device/$deviceId'
    | '/_authenticated/integration/$integrationId'
    | '/_authenticated/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cameras': {
      id: '/_authenticated/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof AuthenticatedCamerasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/energy': {
      id: '/_authenticated/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof AuthenticatedEnergyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenes': {
      id: '/_authenticated/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof AuthenticatedScenesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vacuum': {
      id: '/_authenticated/vacuum'
      path: '/vacuum'
      fullPath: '/vacuum'
      preLoaderRoute: typeof AuthenticatedVacuumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alexa/$deviceId': {
      id: '/_authenticated/alexa/$deviceId'
      path: '/alexa/$deviceId'
      fullPath: '/alexa/$deviceId'
      preLoaderRoute: typeof AuthenticatedAlexaDeviceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alexa/callback': {
      id: '/_authenticated/alexa/callback'
      path: '/alexa/callback'
      fullPath: '/alexa/callback'
      preLoaderRoute: typeof AuthenticatedAlexaCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device/$deviceId': {
      id: '/_authenticated/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/device/$deviceId'
      preLoaderRoute: typeof AuthenticatedDeviceDeviceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integration/$integrationId': {
      id: '/_authenticated/integration/$integrationId'
      path: '/integration/$integrationId'
      fullPath: '/integration/$integrationId'
      preLoaderRoute: typeof AuthenticatedIntegrationIntegrationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/room/$roomId': {
      id: '/_authenticated/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomRoomIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCamerasRoute: typeof AuthenticatedCamerasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnergyRoute: typeof AuthenticatedEnergyRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedScenesRoute: typeof AuthenticatedScenesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedVacuumRoute: typeof AuthenticatedVacuumRoute
  AuthenticatedAlexaDeviceIdRoute: typeof AuthenticatedAlexaDeviceIdRoute
  AuthenticatedAlexaCallbackRoute: typeof AuthenticatedAlexaCallbackRoute
  AuthenticatedDeviceDeviceIdRoute: typeof AuthenticatedDeviceDeviceIdRoute
  AuthenticatedIntegrationIntegrationIdRoute: typeof AuthenticatedIntegrationIntegrationIdRoute
  AuthenticatedRoomRoomIdRoute: typeof AuthenticatedRoomRoomIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCamerasRoute: AuthenticatedCamerasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnergyRoute: AuthenticatedEnergyRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedScenesRoute: AuthenticatedScenesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedVacuumRoute: AuthenticatedVacuumRoute,
  AuthenticatedAlexaDeviceIdRoute: AuthenticatedAlexaDeviceIdRoute,
  AuthenticatedAlexaCallbackRoute: AuthenticatedAlexaCallbackRoute,
  AuthenticatedDeviceDeviceIdRoute: AuthenticatedDeviceDeviceIdRoute,
  AuthenticatedIntegrationIntegrationIdRoute:
    AuthenticatedIntegrationIntegrationIdRoute,
  AuthenticatedRoomRoomIdRoute: AuthenticatedRoomRoomIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
